# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 12:06
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vizmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='municipality',
        ),
        migrations.AddField(
            model_name='dataset',
            name='microsite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vizmanager.Microsite', verbose_name='Microsite'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='render_from',
            field=models.CharField(choices=[('OpenSpending', 'OpenSpending'), ('Babbage-ui', 'Babbage-ui')], default='Babbage-ui', max_length=200),
        ),
        migrations.AddField(
            model_name='theme',
            name='microsite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vizmanager.Microsite', verbose_name='Microsite'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='brand_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=10, verbose_name='Brand Color'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='content_color',
            field=colorfield.fields.ColorField(default='#222222', max_length=10, verbose_name='Content Color'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='sidebar_color',
            field=colorfield.fields.ColorField(default='#888888', max_length=10, verbose_name='Sidebar Color'),
        ),
    ]
