# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizmanager', '0002_auto_20170206_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='render_from',
            field=models.CharField(choices=[('OpenSpending', 'OpenSpending'), ('Babbage-ui', 'Babbage-ui')], default='OpenSpending', max_length=200),
        ),
    ]
