# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizmanager', '0003_auto_20170206_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='render_from',
        ),
        migrations.AddField(
            model_name='microsite',
            name='render_from',
            field=models.CharField(choices=[('OpenSpending', 'OpenSpending'), ('Babbage-ui', 'Babbage-ui')], default='OpenSpending', max_length=200),
        ),
    ]
