# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-04 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizmanager', '0004_auto_20170206_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='initial_dimension',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='viz_type',
            field=models.CharField(choices=[('Treemap', 'Treemap'), ('BarChart', 'BarChart'), ('PieChart', 'PieChart'), ('BubbleTree', 'BubbleTree'), ('Sankey', 'Sankey'), ('Radar', 'Radar'), ('PivotTable', 'PivotTable'), ('Table', 'Table')], max_length=200, verbose_name='Visualization Type'),
        ),
    ]
