# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizmanager', '0007_auto_20170829_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsite',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('de', 'de'), ('es', 'es'), ('el', 'el')], default='en', max_length=2, verbose_name='Language'),
        ),
    ]
