# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizmanager', '0008_auto_20171106_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsite',
            name='kpi_set',
            field=models.ManyToManyField(blank=True, to='vizmanager.KPI'),
        ),
    ]
